steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/my-streamlit-app', '-f', 'app/frontend/Dockerfile', '.']
    dir: '.'

images:
  - 'gcr.io/$PROJECT_ID/my-streamlit-app'
